message("TIM_VX_USE_EXTERNAL_OVXLIB:${TIM_VX_USE_EXTERNAL_OVXLIB}")

set(TIM_VX_USE_EXTERNAL_OVXLIB ON)
set(TIM_VX_ENABLE_VIPLITE OFF)

set(OVXLIB_LIB ${SYNAP_LIBDIR}/libovxlib.so)
set(OVXLIB_INC ${SYNAP_INCDIR}/ovxlib)
set(OVXDRV_INCLUDE_DIRS
    ${SYNAP_INCDIR}
    ${SYNAP_INCDIR}/CL)
